name: pantab tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run lint checks
      run: docker compose run --rm lint ci/scripts/lint_check.sh

  build-linux:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas tableauhyperapi pyarrow
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest

  build-macos:

    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas tableauhyperapi pyarrow
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest

  build-windows:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas tableauhyperapi pyarrow
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Test with pytest
      run: |
        python -m pip install pytest
        python -m pytest
